get http://localhost:3000/phones.json
#index route

###
get http://localhost:3000/phones/3.json
#show route

###
post http://localhost:3000/phones
Content-Type: application/json

{
  "color": "White",
  "edition": "6g",
  "size": "10 in"
}

#update route

###
patch http://localhost:3000/phones/3
Content-Type: application/json

{
  "color": "Purple",
  "edition": "7g",
  "size": "11 in"
}

#update route

###

delete http://localhost:3000/phones/5