get http://localhost:3000/phones.json
#index route

###
get http://localhost:3000/phones/3.json
#show route

###
post http://localhost:3000/phones.json
Content-Type: application/json

{
  "color": "White",
  "edition": "6g",
  "size": "10 in"
}

#create route

###
patch http://localhost:3000/phones/3.json
Content-Type: application/json

{
  "color": "Yellow",
  "edition": "7g",
  "size": "11 in"
}

#update route

###

delete http://localhost:3000/phones/5

###
post http://localhost:3000/user.json
Content-Type: application/json

{
  "name": "amy",
  "email": "@my.com",
  "password": "password"
}

#users create
###
post http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "@my.com",
  "password": "password"
}

#user login
